In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 10],
                    [4, 5, 6, 11],
                    [7, 8, 9, 12]])

# Access the first and third columns (index 0 and 2)
selected_columns = arr[:, [0,2]]
print(selected_columns)
    # Output:
    # [[1 3]
    #  [4 6]
    #  [7 9]]

[[1 3]
 [4 6]
 [7 9]]


In [ ]:
c = np.arange(12).reshape(3,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
c[[0,0,2],[2,3,0]]

array([2, 3, 8])

In [ ]:
b = np.arange(4).reshape(1,4)
b

array([[0, 1, 2, 3]])

In [ ]:
k =c + b

In [ ]:
k[[0,0,2,2],[1,3,0,3]]

array([ 2,  6,  8, 14])

In [ ]:
a = a>5
a


array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
a[]

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
class A:
    def __init__(self):
        print("Hi")

    def func(self):
        print("Hello")

class B(A):  # B inherits from A
    def __init__(self):
        print("sahil")
        super().__init__()

    def func(self):
        print("Bye")
        super().func()

obj = B()
print(obj.func())


sahil
Hi
Bye
Hello
None


In [ ]:
class phone:


  def __init__(self,price,brand,camera):
    print("Inside the phone")
    self.price = price
    self.brand = brand
    self.camera = camera


  def buy(self):
    print("Buying a phone")


class SmartPhone(phone):
  pass



s = SmartPhone(2000,"Apple",14)


Inside the phone


In [ ]:
class phone:


  def __init__(self,price,brand,camera):
    print("Inside the phone")
    self.price = price
    self.brand = brand
    self.camera = camera

class Smartphone(phone):
  def __init__(self,os,ram):
    self.os = os
    self.ram = ram
    print("inside smartphone")


s = Smartphone("Android", 3)

inside smartphone


In [ ]:
class phone:


  def __init__(self,price,brand,camera):
    print("Inside the phone")
    self.__price = price
    self.brand = brand
    self.camera = camera


  def show(self):
    print(self.__price)


class Smartphone(phone):
  def check(self):
    print(self.__price)


s = Smartphone(20000,"Apple",13)
# s.check()
# print(s.brand)
s.show()


Inside the phone
20000


In [ ]:
class  Parents:

  def __init__(self,num):
    self.__num = num

  def get_num(self):
      return self.__num

class Child(Parents):

  def show(self):
    print("This is the child class")



son =  Child(100)
print(son.get_num())
son.show()


100
This is the child class


In [ ]:
class Parents:

  def __init__(self,num):
    self.__num = num

  def get_data(self):
    return self.__num

class Child(Parents):

  def __init__(self, num,val):
    self.__val = val


  def get_val(self):
    return self.__val




son = Child(100,10)
# print(son.get_num())
print(son.get_val())


10


In [ ]:
class phone:


  def __init__(self,price,brand,camera):
    print("Inside the phone")
    self.__price = price
    self.brand = brand
    self.camera = camera

  def purchase(self):
    print("this is the parents")


class Smartphone(phone):

  def purchase(self):
    print("this is  the students")
    super().purchase()




k = Smartphone(20000,"Apple",13)

k.purchase()





Inside the phone
this is  the students
this is the parents


In [ ]:
class phone:


  def __init__(self,price,brand,camera):
    print("Inside the phone")
    self.__price = price
    self.brand = brand
    self.camera = camera


class Smartphone(phone):
    def __init__(self, price, brand, camera,os,ram):
      print("This is parents")
      super().__init__(price, brand, camera)
      self.os = os
      self.ram = ram
      print(" This is child")

s = Smartphone(1000,"Samsung",13,'Anroid',64)
print(s.os)
print(s.ram)



This is parents
Inside the phone
 This is child
Anroid
64


In [ ]:
class Parents:

  def __init__(self,num):
    self.__num = num

  def get_num(self):
    return self.__num

class Child(Parents):

  def __init__(self, num,val):
    super().__init__(num)
    self.__val = val


  def get_val(self):
    return self.__val




son = Child(100,200)
print(son.get_num())
print(son.get_val())


100
200


In [ ]:
class Phone:

  def __init__(self,price,brand,camera):
    print("Inside phone constructor")

  def buy( self):
    print("Buying a phone")

class Smartphone(Phone):
  pass

class Featurephone(Phone):
  pass

Smartphone(1000,"Apple","13px").buy()
Featurephone(500,"Lava","1px").buy()




Inside phone constructor
Buying a phone
Inside phone constructor
Buying a phone


In [ ]:
class Phone:
  def __init__(self,price,brand,camera):
    print("Inside phone")
    self.price = price
    self.brand = brand
    self.camera = camera

  def buy(self):
      print("Buying a phone ")


class Smartphone:

  def review(self):
    print("this is second class")


class Product(Phone,Smartphone):
  pass



s = Product(20000,"Apple",12)


s.buy()



Inside phone
Buyin a phone 


In [ ]:

#Method Overloading
class Shape:

  def area(self,a,b=0):
    if b==0:
      return 3.14*a*a
    else:
      return a*b


s = Shape()

s.area(2)
s.area(3,4)





12

In [123]:

#abstraction

from abc import ABC, abstractmethod


class BankApp(ABC):


  def database(self):
    print("connected to database")

  @abstractmethod
  def security(self):
    pass


In [126]:
class MobileApp(BankApp):


  def login(self):
    print("Mobile login information")


  def security(self):
    print("security")

In [127]:

m = MobileApp()

In [ ]:
m.security()

security


In [137]:
from datetime import date as dt
class Employee:
   def __init__(self, name, age):
      self.name = name
      self.age = age


   def isAdult(age):
      if age > 18:
         return True
      else:
         return False

   @classmethod
   def emp_from_year(emp_class, name, year):
      return emp_class(name, dt.today().year - year)

   def __str__(self):
      return 'Employee Name: {} and Age: {}'.format(self.name, self.age)

# e1 = Employee('Sahil', 2003)
# print(e1)
e2 = Employee.emp_from_year('Subhas', 1987)

print(e2)
# print(Employee.isAdult(25))
# print(Employee.isAdult(16))

Employee Name: Subhas and Age: 38


In [ ]:
# Exercises:
# ● Create a base class Vehicle, with common attributes like plate_no, fuel_type.
# ● Inherit Truck and Van from Vehicle.
# ● Override the is_overloaded() method for each type.


In [121]:
class Vehicle:
    def __init__(self,plate_no,fuel_type):
      self.plate_no = plate_no
      self.fuel_type = fuel_type

    def is_overloaded(self):
        print("The parent is called")

class Truck(Vehicle):

   def __init__(self,plate_no,fuel_type):
    print("this  is the child constructor")


    def is_overloaded(self):
        print("child 1 is called")


class Van(Vehicle):

    def __init__(self, plate_no, fuel_type):
      print("this is cild second ")


    def is_overloaded(self):
        print("child 2 is called")


a = Van(9292,'Petrol')
print(a.is_overloaded())




this is cild second 
child 2 is called
None


In [128]:
# Has - A relationship

class Customer:

  def __init__(self,name,address,gender):
    self.name = name
    self.gender = gender
    self.address = address



class Address:


  def __init__(self,city,pin,state):
    self.__city = city
    self.pin = pin
    self.state = state

  def get_city(self):
    return self.city

add1 = Address('gurgaao',122011,'haryaana')
cust = Customer('Nitish',add1,'male')




In [135]:

def __init__(self,name,address,gender):
    self.name = name
    self.gender = gender
    self.address = address
def print_address(self):
   print(self.address.get_city, self.address.pin,self.address.state)


class Address:


  def __init__(self,city,pin,state):
    self._city = city
    self.pin = pin
    self.state = state

    def get_city(self):
      return self._city


add1 = Address('gurgaao',122011, 'haryana')
cust = Customer('Nitish',add1,'male')

In [ ]:
# ● Add a class variable to count total trucks.
# ● Add @classmethod to get the count.
# ● Implement __str__() for pretty print.
# ● Create TruckFleet class, and define __len__ to return number of trucks.

class Truckfleet:


  def __init__(self,)