In [18]:
import numpy as np


arr = np.array(42)
print(arr)
a1D = np.array([1,2,3,4])
print(a1D)
print(a1D.shape)

42
[1 2 3 4]
(4,)


In [20]:
array1 = np.array(42)
array2 = np.array([1, 2, 3, 4, 5])
array3 = np.array([[1, 2, 3], [4, 5, 6]])
array4 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


print(array1.ndim)
print(array2.ndim)
print(array3.ndim)
print(array4.ndim)

0
1
2
3


In [21]:
a2D = np.array([[1,2],[3,4]])
print(a2D)
print(a2D.shape)

[[1 2]
 [3 4]]
(2, 2)


In [22]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a3D)
print(a3D.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [23]:
import numpy as np

arr1 = np.array([2, 3, 4], dtype=np.uint32)
arr2 = np.array([5, 6, 7], dtype=np.uint32)
print(arr1)
print(arr2)
print(arr1.shape)
print(arr2.shape)

[2 3 4]
[5 6 7]
(3,)
(3,)


In [25]:
arr_3d = np.zeros((2, 3, 4))
print(arr_3d.shape)  # Output: (2, 3, 4)
print(arr_3d)

(2, 3, 4)
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [31]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape((2, 3))
print(new_arr)
# Output:
# [[1 2 3]
#  [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [32]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


In [47]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [46]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0,1,2])



6


In [58]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [64]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [65]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [66]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [67]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3 : -1])

[5 6]


In [68]:
arr[-3:]

array([5, 6, 7])

In [69]:
# Negative end index:
# Slicing stops before the specified position counting backward from the end. For example, my_list[:-2] extracts all elements except the last two.
arr[:-2]

array([1, 2, 3, 4, 5])

In [71]:
print(arr[-4:-1])

[4 5 6]


In [77]:
reversed_list = arr[::-1]
print(reversed_list)

[7 6 5 4 3 2 1]


In [80]:
arr1 = [2,3,4]
arr2 = [4,5,6]
print(np.add(arr1,arr2))

print(np.multiply(arr1,arr2))

[ 6  8 10]
[ 8 15 24]


In [82]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [85]:
print(np.reciprocal(arr))
print(np.power(arr,2)  )

[1 0 0 0 0 0 0]
[ 1  4  9 16 25 36 49]


In [87]:
arr = np.array([5, 15, 20])
arr1 = np.array([2, 5, 9])
print(np.mod(arr,arr1))
print(np.remainder(arr,arr1))

[1 0 2]
[1 0 2]


In [89]:
print(arr.ndim)
print(arr.size)

1
3


In [92]:
print(arr.shape)

(3,)


In [93]:
x = np.array([[1,2,3],[4,5,6]])
print(np.ravel(x))

[1 2 3 4 5 6]


In [94]:
print(np.sin(arr))

[-0.95892427  0.65028784  0.91294525]


In [96]:

arr = np.array([1,2,4,6,8])
print(arr.dtype)

int64


In [98]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [100]:

#copy

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [101]:

# View
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


In [106]:
arr = np.array([1,2,3,4,5])
arr1 = arr.copy()
arr2 = arr.view()
print(arr1.base)
print(arr2.base)

None
[1 2 3 4 5]


In [107]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [108]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [109]:
rr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [110]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [111]:
#iteration on Numpy

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [112]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [113]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [115]:
arr = ([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr):
  print(x)

(array(1), array(5))
(array(2), array(6))
(array(3), array(7))
(array(4), array(8))


In [116]:
arr = np.array([1,2,3])
for idx , x in np.ndenumerate(arr):
  print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [118]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.concatenate((arr1,arr2))
print(arr)
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [123]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

arr = np.vstack((arr1, arr2))

print(arr)
arr = np.dstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [148]:
 arr= np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
 arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [213]:
arr = np.array([[1,2,3],[4,5,6]])
arr


array([[1, 2, 3],
       [4, 5, 6]])

In [220]:
result = arr[[0,1, 1], [0,1,2]]
print(result)

[1 4 5]


In [ ]:
print(arr())

In [204]:
print(arr.shape)

(2, 3)


In [205]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [209]:
array = np.array([10, 20, 30, 40, 50])
print(array[1:4])
print(array[::2])

[20 30 40]
[10 30 50]


In [211]:
matrix = np.array([[0, 1, 2, 3],
                   [4, 5, 6, 7],
                   [8, 9, 10, 11]])

# Select the second row
row2 = matrix[1, :]
print("Second row:", row2)

Second row: [4 5 6 7]


In [228]:
submatrix = matrix[:2, :3]
print("Submatrix of first two rows and three columns:", submatrix)




Submatrix of first two rows and three columns: [[0 1 2]
 [4 5 6]]


In [234]:
# practice: Simulate weather data and do basic computations
import numpy as np
temperatures = np.array([25.5, 26.1, 24.9, 27.0, 25.8])

max_temperature = max(temperatures)
print(max_temperature)

min_temperature = min(temperatures)
print(min_temperature)

avg_temperature = np.average(temperatures)
print(avg_temperature)

standard_deviation = np.std(temperatures)
print(standard_deviation)

27.0
24.9
25.860000000000003
0.694550214167414


In [238]:
# Generate a 2D NumPy array with random integers (10x5) representing temperature readings
from numpy import random
num = random.randint(50, size = (10,5))
print(num)

[[24 15 24 11  1]
 [15  2 32 23 23]
 [34 30 24  2 44]
 [17  7 10 33 45]
 [45 27 38 27 28]
 [44  2 48 30 18]
 [33 45 11  6 18]
 [ 9 31 31 21 18]
 [ 7 23 32 14 21]
 [18 42 28 17 28]]


In [244]:
# Exercise 8:
# Replace all values below 0 with 0.
# Count how many entries are above 30.

num = np.array([[2,-1,8],[-2,-3,3],[3,-5,-2]])

result = np.where(num<0 , 0,num)
print(result)

count_enteries = np.count_nonzero(num > 30)
print(count_enteries)

[[2 0 8]
 [0 0 3]
 [3 0 0]]
0
