In [2]:
# Day 7: Weekly Review + Mini Project
# ● Revise NumPy and core Python
# ● 🧠 Project: Simulate a basic ETL pipeline for IoT data using NumPy
# 🔹 Mini Project:
# Simulate and process IoT sensor data (temperature, humidity, motion):
# ● Generate 1000 entries with timestamps using NumPy.
# ● Filter entries where temperature > 35 and motion detected.
# ● Save to CSV.

import numpy as np

In [3]:
np.full([2, 2], 67, dtype =
 int)

array([[67, 67],
       [67, 67]])

In [4]:
print(np.arange(1,10))

[1 2 3 4 5 6 7 8 9]


In [5]:
print(np.ones([4, 3], dtype = np.int32))


[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [6]:
print(np.full([2,2],67,dtype = int))

[[67 67]
 [67 67]]


In [7]:
arr = np.array([1,2,3,4,5,6,7,8])
num = arr.astype('float')
print(num)

[1. 2. 3. 4. 5. 6. 7. 8.]


In [8]:
arr = np.array([2,3,4,5,7,9,4,5])
num = arr.tolist()
print(num)

[2, 3, 4, 5, 7, 9, 4, 5]


In [9]:
np.save("sahil2.txt",np.arange(5))

In [10]:
np.load("sahil2.txt.npy")

array([0, 1, 2, 3, 4])

In [128]:
np.loadtxt('sahil2.txt', delimiter= ',')

array([[25. , 85.5],
       [30. , 92.1],
       [22. , 78.9]])

In [130]:
np.genfromtxt('/content/pandas.csv',delimiter=',')

array([[ nan,  nan,  nan],
       [ nan, 25. , 85.5],
       [ nan, 30. , 92.1],
       [ nan, 22. , 78.9]])

In [131]:
np.savetxt('sahil2.txt',arr,delimiter= ',')

In [132]:
import numpy as np
original_array  = np.array([1,2,3,4])
copied_array = original_array.copy()


copied_array[0] = 99
print(original_array)
print(copied_array)

[1 2 3 4]
[99  2  3  4]


In [133]:
original_array = np.array([1,2,3,4,5])
view_array = original_array.view()


view_array[0] = 78
print(original_array)
print(view_array)

[78  2  3  4  5]
[78  2  3  4  5]


In [134]:
original_array

b = np.array([[1,2,3,4],[5,6,7,8]])
deleted_array = np.delete(original_array,4)
deleted_array

array([78,  2,  3,  4])

In [135]:
b
deleted_two_d_array = np.delete(b,[2])
deleted_two_d_array
print(b)
print(deleted_two_d_array)

[[1 2 3 4]
 [5 6 7 8]]
[1 2 4 5 6 7 8]


In [13]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,
10, 11, 12, 13, 14, 15, 16])
reshaped_1 = array.reshape((4,array.size//4))
print(reshaped_1)
reshaped_1

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr.resize(3,4)
print(arr)

[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


In [15]:
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
arr = np.array([list_1, list_2])
print(arr.flatten())

[1 2 3 4 5 6 7 8]


In [16]:
gfg = np.array([[1, 2],
 [4, 5],
 [7, 8]])
gfg

array([[1, 2],
       [4, 5],
       [7, 8]])

In [17]:
print(gfg, end ='\n\n')

[[1 2]
 [4 5]
 [7 8]]



In [18]:
print(gfg.transpose(1,0))

[[1 4 7]
 [2 5 8]]


In [19]:
arr1= np.arange(24).reshape(6,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [20]:
print(arr1[[0,1,1],[1,2,3]])

[1 6 7]


In [21]:
an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [3, 4]])
comparison = an_array == another_array
equal_arrays = comparison.all()
print(equal_arrays)

True


In [22]:
arr = np.array([.5, 1.5, 2.5, 3.5, 4.5, 10.1])
print("Square-root:", np.sqrt(arr))

Square-root: [0.70710678 1.22474487 1.58113883 1.87082869 2.12132034 3.17804972]


In [23]:
print("Log Value: ", np.log(arr))

Log Value:  [-0.69314718  0.40546511  0.91629073  1.25276297  1.5040774   2.31253542]


In [24]:
print("Ceil values:", np.ceil(arr))

Ceil values: [ 1.  2.  3.  4.  5. 11.]


In [25]:
print("Floor Values:", np.floor(arr))

Floor Values: [ 0.  1.  2.  3.  4. 10.]


In [26]:
print ("Rounded values:", np.round(arr))

Rounded values: [ 0.  2.  2.  4.  4. 10.]


In [27]:
arr

array([ 0.5,  1.5,  2.5,  3.5,  4.5, 10.1])

In [28]:
print("var of arr:", np.var(arr))

var of arr: 9.688888888888886


In [29]:
print("std of arr:", np.std(arr))

std of arr: 3.1126980079810003


In [30]:
array1 = np.array([0, 1, 2])
array2 = np.array([3, 4, 5])
rslt = np.corrcoef(array1, array2)
print(rslt)

[[1. 1.]
 [1. 1.]]


In [31]:
d = np.arange(10,25,1)

In [136]:
reshaped = b.reshape(2,4)
reshaped

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [137]:
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [138]:
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [33]:
c = np.random.random((2,2))
c

array([[0.65175043, 0.24284612],
       [0.98906046, 0.58363372]])

In [34]:
der =  np.empty((2,3))
der

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [35]:
my_array = np.empty(5)
print(my_array)

# Create a 2x3 array of uninitialized integers
my_2d_array = np.empty((2, 3), dtype=int)
print(my_2d_array)

[ 2.  2.  4.  4. 10.]
[[-4616189618054758400                    0  4607182418800017408]
 [-4616189618054758400                    0  4607182418800017408]]


In [36]:

a = [2,7,9,0,7,8,9,6,5]
a[ : :-1]

[5, 6, 9, 8, 7, 0, 9, 7, 2]

In [37]:
b = np.array([[ 4. ,5. , 6. , 4. ],
 [ 1.5, 2. , 3. , 1.5],
 [ 4. , 5. , 6. , 4. ],
 [ 1.5, 2. , 3. , 1.5]])

print(b[[1,0,1,0],[[0,1,2,0]]])

[[1.5 5.  3.  4. ]]


In [66]:
g = np.array([1,2,3,4,5,6])
g.reshape(3,-2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [139]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
a
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [140]:
np.concatenate((a,b),axis = 0)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [141]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [142]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [143]:
np.hsplit(b,3)

[array([[ 7],
        [10]]),
 array([[ 8],
        [11]]),
 array([[ 9],
        [12]])]

In [144]:
np.vsplit(b,2)

[array([[7, 8, 9]]), array([[10, 11, 12]])]

In [145]:
a = np.arange(30)

In [146]:
a.reshape(3,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [147]:
# Broacasting
a = np.arange(2,10).reshape(2,4)
print(a)
b = np.arange(4).reshape(1,4)
b

c = a+b
c

[[2 3 4 5]
 [6 7 8 9]]


array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12]])

In [148]:
M = np.ones((2, 3))
a = np.arange(3)


In [57]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [58]:
a[:, np.newaxis].shape

(3, 1)

In [149]:
s = np.array([1,2,3,4,5,6])

In [150]:
s = arr[:, np.newaxis]
s


array([[ 0.5],
       [ 1.5],
       [ 2.5],
       [ 3.5],
       [ 4.5],
       [10.1]])

In [64]:
s = arr[np.newaxis, :]
s

array([[ 0.5,  1.5,  2.5,  3.5,  4.5, 10.1]])

In [120]:
# Day 7: Weekly Review + Mini Project
# ● Revise NumPy and core Python
# ● Project: Simulate a basic ETL pipeline for IoT data using NumPy
# Mini Project:
# Simulate and process IoT sensor data (temperature, humidity, motion):
# ● Generate 1000 entries with timestamps using NumPy.
# ● Filter entries where temperature > 35 and motion detected.
# ● Save to CSV.

import numpy as np
reading = 20

temperature = np.random.uniform(10,30,reading)
humidity = np.random.uniform(20,40,reading)
motion_values = np.random.uniform(1,20,reading)


print(temperature)
print(humidity)
print(motion_values)




[26.25616633 17.44301166 23.22086498 21.80541235 16.93747071 17.83877373
 11.574599   14.92285668 28.70583952 21.49166785 28.3986351  24.71013073
 13.39645216 22.44478103 11.62797945 22.46974597 13.83154227 25.64274217
 17.99820284 22.57924983]
[24.42820665 35.29113294 34.64106065 30.2278842  20.32685033 29.60930807
 35.66045569 22.75163281 34.6058393  34.97364776 34.70814657 29.83602833
 28.92414943 27.43949065 33.71960534 37.91697758 31.60004191 25.20112067
 25.72588126 34.97706592]
[11.08576626 10.74579134 10.40555016  4.46316407  9.65562721  5.43967692
  2.08935123 19.66999597  9.97672427 13.97139774  8.45484192 11.46190559
 17.19657156  8.7011913   1.93646148 13.75274568 10.86361361  1.57052107
 14.76689401 16.77911606]


In [111]:
current_date = np.datetime64('today', 'D')
current_date

np.datetime64('2025-07-15')

In [112]:
import numpy as np

arr1 = np.random.randint(1000,size = (1000,3))
arr1

array([[ 36, 197, 478],
       [112, 556, 674],
       [477, 685, 330],
       ...,
       [203, 270,  45],
       [501, 685, 877],
       [664, 785,  21]])

In [113]:
start_date = np.datetime64('today','D')


In [94]:
end_date = np.datetime64('2028-04-10','D')

In [114]:

start_datetime = np.datetime64('2025-07-15T00:00:00')

timestamps = np.arange(start_datetime, start_datetime + np.timedelta64(1000, 'D'), dtype='datetime64[D]')

print(timestamps)

['2025-07-15' '2025-07-16' '2025-07-17' '2025-07-18' '2025-07-19'
 '2025-07-20' '2025-07-21' '2025-07-22' '2025-07-23' '2025-07-24'
 '2025-07-25' '2025-07-26' '2025-07-27' '2025-07-28' '2025-07-29'
 '2025-07-30' '2025-07-31' '2025-08-01' '2025-08-02' '2025-08-03'
 '2025-08-04' '2025-08-05' '2025-08-06' '2025-08-07' '2025-08-08'
 '2025-08-09' '2025-08-10' '2025-08-11' '2025-08-12' '2025-08-13'
 '2025-08-14' '2025-08-15' '2025-08-16' '2025-08-17' '2025-08-18'
 '2025-08-19' '2025-08-20' '2025-08-21' '2025-08-22' '2025-08-23'
 '2025-08-24' '2025-08-25' '2025-08-26' '2025-08-27' '2025-08-28'
 '2025-08-29' '2025-08-30' '2025-08-31' '2025-09-01' '2025-09-02'
 '2025-09-03' '2025-09-04' '2025-09-05' '2025-09-06' '2025-09-07'
 '2025-09-08' '2025-09-09' '2025-09-10' '2025-09-11' '2025-09-12'
 '2025-09-13' '2025-09-14' '2025-09-15' '2025-09-16' '2025-09-17'
 '2025-09-18' '2025-09-19' '2025-09-20' '2025-09-21' '2025-09-22'
 '2025-09-23' '2025-09-24' '2025-09-25' '2025-09-26' '2025-09-27'
 '2025-09-

In [126]:
import numpy as np
import datetime

temperature_data = np.random.normal(loc=30, scale=5, size=1000)


humidity_data = np.random.normal(loc=60, scale=10, size=1000)


motion_data = np.random.choice([0, 1], size=1000)


start_time = np.datetime64('2025-07-15T00:00:00')
timestamps = np.arange(start_time, start_time + np.timedelta64(1000, 's'), np.timedelta64(1, 's'))

iot_data = np.array(list(zip(timestamps, temperature_data, humidity_data, motion_data)),
                    dtype=[('timestamp', 'datetime64[s]'), ('temperature', 'f4'), ('humidity', 'f4'), ('motion', 'i4')])

print("Generated IoT Data Sample (First 5 Entries):")
print(iot_data[:5])



filtered_data = iot_data[(iot_data['temperature'] > 35) & (iot_data['motion'] == 1)]

print("\nFiltered IoT Data (Temperature > 35 and Motion Detected):")
print(filtered_data)
print(f"\nNumber of filtered entries: {len(filtered_data)}")

Generated IoT Data Sample (First 5 Entries):
[('2025-07-15T00:00:00', 28.660604, 56.956703, 0)
 ('2025-07-15T00:00:01', 27.040167, 78.38772 , 1)
 ('2025-07-15T00:00:02', 34.78913 , 65.79672 , 0)
 ('2025-07-15T00:00:03', 33.903687, 58.01242 , 0)
 ('2025-07-15T00:00:04', 29.947084, 49.901093, 0)]

Filtered IoT Data (Temperature > 35 and Motion Detected):
[('2025-07-15T00:00:05', 36.546124, 57.62178 , 1)
 ('2025-07-15T00:00:13', 35.743748, 47.522335, 1)
 ('2025-07-15T00:00:16', 36.8137  , 58.683914, 1)
 ('2025-07-15T00:00:22', 35.461926, 37.942722, 1)
 ('2025-07-15T00:00:27', 36.18277 , 60.78073 , 1)
 ('2025-07-15T00:00:31', 35.916824, 48.448906, 1)
 ('2025-07-15T00:00:39', 35.64528 , 65.89451 , 1)
 ('2025-07-15T00:00:48', 41.677624, 42.66256 , 1)
 ('2025-07-15T00:01:32', 35.060425, 58.60383 , 1)
 ('2025-07-15T00:01:44', 36.28784 , 70.65935 , 1)
 ('2025-07-15T00:01:45', 40.599136, 57.4694  , 1)
 ('2025-07-15T00:01:58', 39.666824, 74.455   , 1)
 ('2025-07-15T00:01:59', 37.83188 , 61.882473