In [11]:
import numpy as np


# Aggregating functions and Transformation
a = np.array([1,2,3,4,5,6,7,8,9,10])
mean_avg = np.mean(a)
mean_avg

np.float64(5.5)

In [13]:
b = np.array([[1,2,3],[4,5,6]])
b
ans_matrix = np.mean(b,axis = 0)
ans_matrix

array([2.5, 3.5, 4.5])

In [17]:
ans_matrix = np.sum(b,axis = 0)
ans_matrix

array([5, 7, 9])

In [15]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
ans_matrix = np.std(b,axis=0)
ans_matrix

array([1.5, 1.5, 1.5])

In [21]:
max_matrix = np.max(b,axis=0)
max_matrix

array([4, 5, 6])

In [22]:
min_matrix = np.min(b,axis = 1)
min_matrix

array([1, 4])

In [23]:
prod_matrix = np.prod(b,axis = 0)
prod_matrix

array([ 4, 10, 18])

In [24]:
prod_matrix = np.prod(b,axis = 1)
prod_matrix

array([  6, 120])

In [45]:
per_matrix = np.percentile(b,100,axis = 0)
per_matrix

array([4., 5., 6.])

In [30]:
arg_min_matrix =  np.argmin(b,axis = 0)
arg_min_matrix

array([0, 0, 0])

In [31]:
arg_max_matrix =  np.argmax(b,axis = 0)
arg_max_matrix

array([1, 1, 1])

In [33]:
numpy_any_function = np.any( b,axis = 1)
numpy_any_function

array([ True,  True])

In [34]:
numpy_all_function = np.all(b,axis = 1)
numpy_all_function

array([ True,  True])

In [36]:
#Boolean Indexing in Numpy

array1 = np.array([12,24,16,21,32,29,7,15])
boolean_mask = array1 > 20
boolean_mask
array1[boolean_mask]

array([24, 21, 32, 29])

In [38]:
array1 = np.array([1, 2, 4, 9, 11, 16, 18, 22, 26, 31, 33, 47, 51, 52])
boolean_mask = (array1 < 10) | (array1 > 40)
result = array1[boolean_mask]
print(result)


[ 1  2  4  9 47 51 52]


In [40]:
array1 = np.array([[1, 7, 9],
                    [14, 19, 21],
                    [25, 29, 35]])

boolean_mask = array1 > 9
result = array1[ boolean_mask]
print(result)

[14 19 21 25 29 35]


In [42]:
A = np.array([3,4,6,10,24,89,45,43,46,99,100])
print(A[(A %3==0) & (A % 5==0)])

[45]


In [54]:
import numpy as np

arr = np.array([1, 7, 3, 9, 2, 6])
result = np.where(arr > 5, 0, arr)
print(result)

[1 0 3 0 2 0]


In [53]:
arr1 = np.array([30,23,67,12,8,9,4])
result1 = np.where(arr1 > 20,0,arr1)
print(result1)


[ 0  0  0 12  8  9  4]


In [56]:
arr1 = np.array([30,23,67,12,8,9,4])
result1 = np.where((arr1>20)&(arr1<30),0,arr1)
print(result)

[1 0 3 0 2 0]


In [57]:
arr1 = np.array([30,23,67,12,8,9,4])
result1 = np.where(arr1 > 25,np.nan,arr1)
print(result1)

[nan 23. nan 12.  8.  9.  4.]


In [61]:
# Mini Project: Build a metrics dashboard using simulated data




In [68]:
# Exercise 9:
# Given a 2D NumPy array of daily sensor data (rows: days, cols: sensors):
# Compute the average per sensor.
# Find the day with maximum total reading.


sensor_data = np.array([[1,2,3,4,5,6,7],[20,14,17,19,23,32,43]])
sensor_data


avg_per_sensor = np.mean(sensor_data)
avg_per_sensor

max_total_reading = np.max(sensor_data,axis=0)
max_total_reading


array([20, 14, 17, 19, 23, 32, 43])

In [74]:
avg_per_sensor = np.average(sensor_data,axis = 0)
avg_per_sensor

array([10.5,  8. , 10. , 11.5, 14. , 19. , 25. ])

In [71]:
max_total_reading = np.max(sensor_data)
max_total_reading

np.int64(43)

In [78]:
iterable = (a for a in range(8))
print(np.fromiter(iterable,int))

[0 1 2 3 4 5 6 7]


In [79]:
print(np.empty([4,3], dtype=int))

[[          912066627                   0     139465041361888]
 [           10767936     139465041403344            10765928]
 [            9924928             9924928             9924928]
 [            9924928 6568633515958755594      45480266443826]]


In [80]:
a = np.full([2,2],67,dtype = int)
a

array([[67, 67],
       [67, 67]])

In [81]:
b = np.eye(4)
print(b)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Without seed:
[0.68423303 0.44015249 0.12203823]
[0.49517691 0.03438852 0.9093204 ]

With seed 42:
[0.37454012 0.95071431 0.73199394]

Running again with seed 42:
[0.37454012 0.95071431 0.73199394]


In [8]:
# Mini Project: Metrics Dashboard with Simulated Data
# Objective
# Create a simple sensor metrics dashboard that:

# Simulates daily sensor readings

# Calculates key metrics:

# Mean, Sum, Standard Deviation per sensor

import numpy as np
readings = np.array([[1,2,3,4,5,6],[20,22,32,40,45,55]])
readings


mean_values = np.mean(readings,axis = 0)
mean_values

In [12]:
sum_values = np.sum(readings,axis = 0)
sum_values

array([21, 24, 35, 44, 50, 61])

In [13]:
std_devation = np.std(readings,axis=0)
std_devation

array([ 9.5, 10. , 14.5, 18. , 20. , 24.5])

In [ ]:
import pandas as pd
import numpy as np

# Assuming 'data_mixed.csv' exists:
# Name,Age,Score
# Alice,25,85.5
# Bob,30,92.1
# Charlie,22,78.9


df = pd.read_csv('/content/pandas.csv')
arr = df.to_numpy() # Converts the entire DataFrame to a NumPy array
print(arr)

# If you only want specific columns as a numerical array:
numerical_arr = df[['Age', 'Score']].to_numpy()
print(numerical_arr)

In [ ]:
import numpy as np

# Time series of stock prices
stock_prices = np.array([150.25, 152.75, 153.50, 155.00, 154.25])

# Calculate the daily change in stock prices
price_changes = np.diff(stock_prices)

print("Price Changes:", price_changes)

In [14]:
import numpy as np

date_only = np.datetime64('2025-07-14')
datetime_full = np.datetime64('2025-07-14T17:58:00')
current_time = np.datetime64('now')
current_date_day_res = np.datetime64('today', 'D')

In [15]:
import numpy as np
date1 = np.datetime64('2025-07-01')
date2 = np.datetime64('2025-07-10')
time_difference = date2 - date1  # Result is a timedelta64
future_date = date1 + np.timedelta64(5, 'D') # Add 5 days

In [16]:
import numpy as np

# get the current date and time
result = np.datetime64('now')

print("Current date and time:")
print(result)

Current date and time:
2025-07-14T14:01:11


In [17]:
import numpy as np

# get the current date
date_today = np.datetime64('today', 'D')

print("Today's date:")
print(date_today)

Today's date:
2025-07-14


In [18]:
import numpy as np

# use datetime64() for different time units
year = np.datetime64('2025', 'Y')
month = np.datetime64('2025-07', 'M')
day = np.datetime64('2025-07-29', 'D')
hour = np.datetime64('2025-07-29T10', 'h')
minute = np.datetime64('2025-07-29T10:30', 'm')
second = np.datetime64('2025-07-29T10:30:15', 's')

print("Year: ", year)
print("Month: ", month)
print("Day: ", day)
print("Hour: ", hour)
print("Minute: ", minute)
print("Second: ", second)

Year:  2025
Month:  2025-07
Day:  2025-07-29
Hour:  2025-07-29T10
Minute:  2025-07-29T10:30
Second:  2025-07-29T10:30:15


In [19]:
import numpy as np
from datetime import datetime

dt64 = np.datetime64("2025-07-29T12:34:56")

dt = dt64.astype(datetime)

print(dt)

2025-07-29 12:34:56


In [20]:
import numpy as np
from datetime import datetime

dt = datetime(2025,7,14,12,34,56)

dt64 = np.datetime64(dt)

print(dt64)

2025-07-14T12:34:56.000000


In [21]:
def memory_efficient_function(max_value):
    current_value = 0
    while current_value < max_value:
        yield current_value
        current_value += 1

# Using the generator function
my_generator = memory_efficient_function(5)

for value in my_generator:
    print(value)

0
1
2
3
4


In [22]:
# Exercise 10:
# Simulate one week of hourly power consumption data:
# 7x24 matrix.
#Calculate total, average, and variance per day.
a = np.random.randint(100,size = (7,24))
print(a)


total_per_day = np.sum(a)
print(total_per_day)


avergae_per_day = np.average(a)
avergae_per_day


variance_per_day = np.var(a)
variance_per_day

[[ 1 56 39 25 67 23  4 91 43 35  6 26 33 43 85 24 68 54 20  4 39 16 12 78]
 [15 67 51 60 41 77  8 92 99 15 54 53 45 82 84 14 27 29 29 69 90 85 65 42]
 [ 6 44 79 80 76 43 88 95 76 33 71 90 37 15 35 84 11 99 81 94  2 20 80 97]
 [43 41 91 82 29 22 56 72 25 21  3 26  1 85 16 59 99 31 66 87 20  5 62 10]
 [28  9 85 92 40 18 10  8  6 85 47 87  8 94 61 43 52 36 36  9 39 46 88 68]
 [74  8 44 17 93  6 39 67 17 72 20 40 26 30 34 15 93 91 71 16 75 42 10 14]
 [18  2 24 12 94 70 57 59 28 69 24 70 91 63 54 24 57 25 13 91 78 55 22 56]]


In [23]:
import numpy as np

# create a range of dates from 2023-04-01 to 2023-04-10
dates = np.arange('2023-04-01', '2023-04-11', dtype='datetime64[D]')

# print the dates
print(dates)





['2023-04-01' '2023-04-02' '2023-04-03' '2023-04-04' '2023-04-05'
 '2023-04-06' '2023-04-07' '2023-04-08' '2023-04-09' '2023-04-10']
